# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 450a3ae244eab466a0853b7e1583d800986cfdb0cf0d0c77861ca2d20d5cf8a097ec4e45d01d1ff8174a494823e4a484e8455317b0f2a74efb527050c487fd28

test:
  secret_key_base: aabf5efeead9248b84c646da0c0d8c51bc158242a85015d76c2634766627eada65b0dc1ff8a218df4f958909a9ef75017d0333e443041c19d85a4a3e6973cf23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
